/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/editor/components/e-header copy.vue')['default']
    EBar: typeof import('./src/editor/components/e-bar/e-bar.vue')['default']
    EContent: typeof import('./src/editor/components/e-content.vue')['default']
    EFooter: typeof import('./src/editor/components/e-footer.vue')['default']
    EHeader: typeof import('./src/editor/components/e-header.vue')['default']
    ETransistion: typeof import('./src/editor/components/e-transistion.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NInput: typeof import('naive-ui')['NInput']
    NSelect: typeof import('naive-ui')['NSelect']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/editor/components/test.vue')['default']
  }
}
