/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EBar: typeof import('./src/editor/components/e-bar/e-bar.vue')['default']
    ECard: typeof import('./src/editor/components/e-card/e-card.vue')['default']
    EContent: typeof import('./src/editor/components/e-content.vue')['default']
    EFooter: typeof import('./src/editor/components/e-footer.vue')['default']
    EHeader: typeof import('./src/editor/components/e-header.vue')['default']
    ESidebar: typeof import('./src/editor/components/e-sidebar/e-sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/editor/components/test.vue')['default']
  }
}
